apiVersion: apps/v1
kind: Deployment
metadata:
  name: portail
  namespace: portail-system
  labels:
    app: portail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portail
  template:
    metadata:
      labels:
        app: portail
      annotations:
        k8s.v1.cni.cncf.io/networks: vpc-frontend, vpc-backend
    spec:
      serviceAccountName: portail-controller
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - name: portail
        image: ghcr.io/epheo/portail:latest
        args: ["--kubernetes"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
