apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespaces.yaml
- networks.yaml
- deployment.yaml
- gateway.yaml
- tcproute.yaml
- referencegrant.yaml
- backend.yaml
patches:
- path: rbac-patch.yaml
