apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment.yaml
- gateway-frontend.yaml
- gateway-backend.yaml
- httproute.yaml
patches:
- path: rbac-patch.yaml
