apiVersion: gateway.networking.k8s.io/v1
date: "2026-03-30T12:15:17Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.4.1
implementation:
  contact:
  - '@epheo'
  organization: epheo
  project: portail
  url: https://github.com/epheo/portail
  version: v0.1.0
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 25
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayInfrastructurePropagation
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteCORS
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 2
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayHTTPListenerIsolation
    - GatewayPort8080
    - GatewayStaticAddresses
    unsupportedFeatures:
    - GatewayInfrastructurePropagation
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- GatewayOptionalAddressValue
- HTTPRouteNamedRule
- HTTPRouteRequestPercentageMirror
- UDPRoute
